spring:
  datasource:
    username: customvoca
    password: customvoca
    url: jdbc:mariadb://localhost:13306/customvoca?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate


file:
  bbs-upload-dir: /home/gumin/Desktop/upload/customvoca/bbs-file
  word-image-dir: /home/gumin/Desktop/upload/customvoca/word-file
  vocabulary-thumbnail-image-dir: /home/gumin/Desktop/upload/customvoca/vocabulary-file

logging:
  level:
    project.study.jgm.customvocabulary: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: info #spring security에 대해 어떤 메세지가 출력이 되는지 확인

