spring:
  datasource:
    username: customvoca
    password: customvoca
    url: jdbc:mariadb://localhost:3306/customvoca
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug #spring security에 대해 어떤 메세지가 출력이 되는지 확인

jwt-security:
  secret-key: costomvocaSecretKey
  token-valid-second: 300
  expiration-cycle-days: 14


